version: '3.7'
name: 'cinema-prod'

services:
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    restart: unless-stopped

  app:
    build: ./app
    container_name: app
    env_file:
      - .env
    depends_on:
      - elastic
      - redis
    restart: unless-stopped

  elastic:
    image: elasticsearch:8.6.2
    container_name: elastic
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
