version: '3'
services:
  service:
    build: ./app
    container_name: service
    env_file:
      - .env
    depends_on:
      - elastic
    ports:
      - "8000:8000"

  elastic:
    image: elasticsearch:8.6.2
    container_name: elastic
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
