[tool.isort]
profile = "black"
py_version = "310"
line_length = 120

[tool.black]
line-length = 120
target-version = ['py310']

[tool.flake8]
ignore = ['E231', 'E241', 'W191']
per-file-ignores = [
    '__init__.py:F401',
]
max-line-length = 120
count = true
